export const ZH_TEXT = {
  title: '对话',
  settingsTitle: '设置',
  settingsTabGeneral: '常规',
  settingsTabMcp: 'MCP 插件',
  settingsTabRpc: '直连 RPC 调试',
  threadId: '会话线程 ID',
  noThread: '当前尚未建立线程',
  clearConversation: '清空对话',
  newConversation: '新建对话',
  conversationHistory: '对话历史',
  noConversation: '暂无对话',
  loadingConversations: '正在加载对话...',
  loadingMessages: '正在加载历史消息...',
  deletingConversation: '删除',
  deleteConversation: '删除对话',
  confirmDeleteConversation: '确定要清空这个对话吗？',
  conversationLoadFailed: '获取对话列表失败',
  emptyTitle: '开始对话',
  emptyDescription: '直接发送第一条消息即可，模型与接口由后端统一调度。',
  composerPlaceholder: '输入你的问题...（Enter 发送，Shift+Enter 换行）',
  send: '发送',
  sending: '发送中',
  ariaOpenSettings: '打开设置面板',
  ariaCloseSettings: '关闭设置面板',
  ariaOpenSidebar: '打开对话列表',
  ariaCloseSidebar: '关闭对话列表',
  ariaSwitchToLight: '切换到浅色模式',
  ariaSwitchToDark: '切换到深色模式',
  errRequestFailed: '请求失败',
  errUnknown: '请求模型回复失败。',

  backendManagedTitle: '后端托管模式',
  backendManagedDescription:
    '接口地址、鉴权和模型参数统一由后端环境变量控制，前端不再提供手动配置。',
  backendManagedHint: '模型与接口由后端统一配置',

  toolBusy: '工具执行中',
  toolDone: '工具执行完成',
  toolError: '工具执行异常',
  toolRunningTitle: '正在调用函数',
  toolSelectedTitle: '本轮候选工具',
  toolRealtimeTitle: '实时工具事件',
  toolEventStart: '开始',
  toolEventEnd: '结束',

  mcpTitle: 'MCP 插件管理',
  mcpRefresh: '刷新状态',
  mcpReindex: '重建工具索引',
  mcpEnable: '启用',
  mcpDisable: '停用',
  mcpServers: '服务器列表',
  mcpTools: '工具列表',
  mcpNoServer: '暂无插件服务器',
  mcpNoTool: '暂无工具',
  mcpServerId: '插件 ID',
  mcpCommand: '启动命令',
  mcpArgs: '命令参数',
  mcpCwd: '工作目录',
  mcpDescription: '描述',
  mcpOptionalPlaceholder: '可留空',
  mcpSelectPlaceholder: '请选择',
  mcpArgsPlaceholder:
    '支持两种写法：\n1) -y chrome-devtools-mcp@latest\n2) ["-y","chrome-devtools-mcp@latest"]',
  mcpEnableOrUpdate: '启用/更新插件',
  mcpRouterStatus: '路由状态',
  mcpRpcTitle: '直连 RPC 调试',
  mcpRpcServer: 'server_id',
  mcpRpcTool: 'tool_name',
  mcpRpcArgs: 'arguments(JSON)',
  mcpRpcCall: '调用工具',
  mcpRpcResult: '调用结果',
  mcpRpcInvalidJson: 'arguments 不是合法 JSON 对象。',
} as const
