export const ZH_TEXT = {
  title: 'Lobe 风格 AI 对话',
  noModel: '未选择模型',
  settingsTitle: '模型设置',
  apiUrl: '接口地址',
  apiUrlPlaceholder: 'https://api.openai.com/v1',
  apiKey: '接口密钥',
  apiKeyPlaceholder: '请输入 API Key',
  model: '模型',
  customModel: '自定义模型',
  customModelName: '自定义模型名',
  customModelPlaceholder: '例如：deepseek-chat / qwen-max / claude-3-7-sonnet',
  systemPrompt: '系统提示词',
  clearConversation: '清空对话',
  emptyTitle: '开始对话',
  emptyDescription: '先填写接口地址、密钥和模型，然后发送第一条消息。',
  composerPlaceholder: '请输入你的问题...（Enter 发送，Shift+Enter 换行）',
  send: '发送',
  sending: '发送中',
  ariaOpenSettings: '打开设置面板',
  ariaCloseSettings: '关闭设置面板',
  ariaSwitchToLight: '切换到浅色模式',
  ariaSwitchToDark: '切换到深色模式',
  customModelOption: '使用自定义模型...',
  errApiUrlRequired: '接口地址不能为空。',
  errModelRequired: '请选择模型。',
  errApiKeyRequired: '接口密钥不能为空。',
  errRequestFailed: '请求失败',
  errUnknown: '请求模型回复失败。',
  errEmptyPayload: '模型返回内容为空。',
  errNoText: '模型未返回可读文本。',
} as const
